name: Publish the Enclave CC release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asset:
          - HW
          - SIM
    steps:
      - name: Login to quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.COCO_QUAY_DEPLOYER_USERNAME }}
          password: ${{ secrets.COCO_QUAY_DEPLOYER_PASSWORD }}

      - uses: actions/checkout@v3
      - name: Build Enclave CC Payload using SGX_MODE=${{ matrix.asset }}
        run: |
          ./tools/packaging/build/build_payload.sh 
        env:
          SGX_MODE: ${{ matrix.asset }}
          CI: no
          PUSH: yes
